version: '3'
services:
  database:
    container_name: "postgres_db"
    image: "postgres:11" # use latest official postgres version
    env_file:
      - database.env # configure postgres
    ports:
      - 5432:5432
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
      - /Users/tranquanghuy/BillSplitter/seed:/var
volumes:
  database-data: # named volumes can be managed easier using docker-compose